### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ZarinNegah** [MTProto/MTProtoProxy#1]
Hello
We tried to set up my friend and me
But we did not succeed
It is possible to put a complete setup video or complete the steps

**Comment by MTProto** [comment]
Could you please tell exactly what you have done and whether there were any errors or not?
steps to create server:

```
npm install mtprotoproxy
node ./app.js
```
Remember that you have to write "app.js" **yourself** or use one of my sample codes as "app.js"

**Comment by ZarinNegah** [comment]
[root@CentOS7-4gb-nbg1-MTP ~]# npm install mtprotoproxy
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.


-------------------------------------------------

[root@CentOS7-4gb-nbg1-MTP ~]# node ./app.js
module.js:550
    throw err;
    ^

Error: Cannot find module './mtprotoproxy'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/app.js:3:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

**Comment by MTProto** [comment]
Sorry that was my mistake. I was reading module locally. I have corrected README file. Please check it. Please do not hesitate to ask me about the problems.

**Comment by ZarinNegah** [comment]
npm install mtprotoproxy
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

+ mtprotoproxy@1.0.5
added 58 packages from 68 contributors and audited 76 packages in 5.858s
found 0 vulnerabilities


---------------------------------------------------------------------
do not work dear

**Comment by MTProto** [comment]
Thats not a problem. This is a warning. Not important as you have not initialized npm. If you install any npm package without npm init you will get that warning.If that is important for you first enter ```npm init``` and fill the request. Then enter ```npm install mtprotoproxy```

**Comment by MTProto** [comment]
Is there any problem remained?
