### ISSUE TITLE
Dc5 Data Center Connection Failed

### ISSUE THREAD

**Issue by aa1008611** [MTProto/MTProtoProxy#13]
Thank you

**Comment by MTProto** [comment]
Did you test it on one server only? This problem occurs mainly when the connection pool to the telegram is empty and the main reason is that your server is inside the countries which intentionally slows the connection to telegram server. If you have any other experience please let me know.

**Comment by aa1008611** [comment]
china

**Comment by aa1008611** [comment]
Python 3 version asynchronous mtproto for alexbers,Solved by modifying the MAX _ CONNS _ IN _ POOL = 1

**Comment by aa1008611** [comment]
Both versions of MTP are installed on the same server. Your connection is slow. The asynchronous version has been fixed.

**Comment by aa1008611** [comment]
And how to restart and self-start the proxy.

**Comment by aa1008611** [comment]
Excuse me, how to restart the agent?

**Comment by aa1008611** [comment]
The DC 5 data center is not connected，Connection failed
