### ISSUE TITLE
Why gives this error when running ؟

### ISSUE THREAD

**Issue by ali172** [MTProto/MTProtoProxy#2]
New client: { id: 75, address: '**********', port: 3855 }
Client left: { id: 75,
  bytesWritten: 0,
  bytesRead: 177,
  error:
   'Error: Assertion failed: No matching secret\n    at assertit (/root/proto/node_modules/mtprotoproxy/index.js:54:9)\n    at handleClient (/root/proto/node_modules/mtprotoproxy/index.js:445:2)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }

**Comment by MTProto** [comment]
This is just for your information. This is not a critical error. If a client tries to use a wrong secret, server will show this message. You can simply skip this.
For example consider that you have set 00000000000000000000000000000000 as secret in your source code. User should use dd00000000000000000000000000000000 as client secret, but he/she uses a wrong secret instead e.g. ddaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.
Then server will notify admin that a user has used a wrong secret.
If you have any problem do not hesitate to tell me.

**Comment by ali172** [comment]
Hi, thanks
   Again, he makes the same mistake

server
let telegram=new MTProtoProxy(
		{
			secrets:[Buffer.from('dddddddddddddddddddddddddddddddd','hex')],
			tag:   Buffer.from('cae554f8cbafba5b343a2d4f72e2f8e4','hex'),
			httpServer,
			async filter(){}
		}
	);
======================================================
client
https://t.me/proxy?server=XXXXXXXXX&port=8080&secret=dddddddddddddddddddddddddddddddd

error
New client: { id: 2, address: 'XXXXXXX', port: 2170 } on core  2
Client left: { id: 2,
  bytesWritten: 0,
  bytesRead: 205,
  error:
   'Error: Assertion failed: No matching secret\n    at assertit (/root/mtproto/node_modules/mtprotoproxy/index.js:54:9)\n    at handleClient (/root/mtproto/node_modules/mtprotoproxy/index.js:445:2)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' } on core  2

**Comment by MTProto** [comment]
You are using wrong secret. Please remember that secret in server code should be 32 character, and for the client, it should have 34 character. Your secret on the link you provided is 32 character long. Just change it to 34 character i.e. secret=dddddddddddddddddddddddddddddddddd (34 d character and not 32 character).

**Comment by ali172** [comment]
Thank you
  fixed

**Comment by MTProto** [comment]
You're welcome.
