### ISSUE TITLE
Default proxy sponser

### ISSUE THREAD

**Issue by idotnetdev** [MTProto/MTProtoProxy#5]
سلام و عرض ادب
من از اسکریپت شما استفاده کردم و دیدم که یه کانالی رو به عنوان کانال اسپانسر پروکسی میاره که اصلا من ست نکردم.
چرا اینطوریه و چطوری میتونم حذفش کنم؟ نمی خوام اسپانسر داشته باشه
ممنون

**Comment by MTProto** [comment]
Read the documentation please and MIT license. 
Use your own "adtag" instead of the one provided in the fastsetup.sh fie. You have to override it. Project is distributed under MIT license and is open source; It means that you can double check the code and you are free to change the code as well.
