### ISSUE TITLE
Secret is incorrect

### ISSUE THREAD

**Issue by taha-ghadirian** [MTProto/MTProtoProxy#6]
Hello. I have a secret like this: dd12378924568212538749552778952756
its work in telegram, but when adding it in @MTProxybot its says: 

**Incorrect secret value. It must contain 32 hex characters like 
00112233445566778899aabbccddeeff.**

can any one help me? :(

**Comment by taha-ghadirian** [comment]
@MTProto

**Comment by hamid814** [comment]
try entering the secret without the first ```dd``` or ```ee```
