### ISSUE TITLE
Sponsor channel is not shown 

### ISSUE THREAD

**Issue by hypercianstand** [MTProto/MTProtoProxy#8]
hi
how  and where can i get adtag ?

**Comment by MTProto** [comment]
Use @MTProxybot which is the official bot of the telegram MTProto Proxies. First you have to register your server and after that you can assign a channel as promotion channel. After that you can use the proxy tag.

**Comment by hypercianstand** [comment]
> 
@MTProto
When i use MTProtxybot it says

Incorrect secret value. It must contain 32 hex characters like 
00112233445566778899aabbccddeeff.

i used 32 characters of zero in the bot and i got this tag

Success!
Your proxy has been successfully registered. You can now pass this proxy tag to the software you are using: 30e5d73419aa335e0116060c665b8b70.
Here is a link to your proxy server: https://t.me/proxy?server=1*7.**.***.1*5&port=443&secret=00000000000000000000000000000000

but my sponsor channel is not shown
